/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;
import config.Koneksi; // Import kelas Koneksi kamu
import java.sql.Connection;
// import java.sql.DriverManager; // Tidak diperlukan lagi
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// import java.sql.Connection; // Duplikat
// import java.sql.DriverManager; // Duplikat
import java.sql.PreparedStatement;
// import java.sql.ResultSet; // Duplikat
// import java.sql.SQLException; // Duplikat
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date; // Penting untuk tipe data DATE
import java.sql.Types; // Untuk penanganan null pada PreparedStatement
// import java.sql.*; // Duplikat, sudah ada import spesifik
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author fitri
 */
public class AdminDataSiswa extends javax.swing.JFrame {
    private int idAdmin;

    /**
     * Creates new form AdminDataSiswa
     */
    public AdminDataSiswa(int idAdmin) {
        this.idAdmin = idAdmin;
        initComponents();
        setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
        buttonGroup1.add(rbLaki); // Menambahkan radio button ke group
        buttonGroup1.add(rbPerempuan); // Menambahkan radio button ke group
        loadTableData(); // Muat data awal saat frame dibuat
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATASISWA = new javax.swing.JTable();
        btnLIHATDATA = new javax.swing.JButton();
        btnKEMBALI = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idanggota = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_NIS = new javax.swing.JTextField();
        txt_tanggallahir = new javax.swing.JTextField();
        btnHAPUS = new javax.swing.JButton();
        btnSIMPAN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_kelas = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA SISWA");

        tblDATASISWA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No ", "Nama", "NIS", "Kelas", "Tanggal Lahir", "Jenis Kelamin", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(tblDATASISWA);

        btnLIHATDATA.setText("LIHAT DATA");
        btnLIHATDATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIHATDATAActionPerformed(evt);
            }
        });

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Anggota");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("NIS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Lahir");

        btnHAPUS.setText("HAPUS");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        btnSIMPAN.setText("SIMPAN");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Alamat");

        rbPerempuan.setText("Perempuan");

        rbLaki.setText("Laki - laki");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Kelas");

        txt_password.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHAPUS)
                        .addGap(18, 18, 18)
                        .addComponent(btnUPDATE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLIHATDATA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnKEMBALI))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tanggallahir, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_idanggota, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_NIS, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_alamat)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbLaki)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbPerempuan)))
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(txt_username)
                                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSIMPAN)
                .addGap(262, 262, 262))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnKEMBALI)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_NIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_tanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(rbLaki)))
                            .addComponent(rbPerempuan))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSIMPAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLIHATDATA)
                    .addComponent(btnUPDATE)
                    .addComponent(btnHAPUS))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        dispose();
        AdminDashboard guestPage = new AdminDashboard(idAdmin);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void tblDATASISWAMouseClicked(java.awt.event.MouseEvent evt) {                                        
        int selectedRow = tblDATASISWA.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDATASISWA.getModel();

        txt_idanggota.setText(model.getValueAt(selectedRow, 0).toString()); // ID Anggota
        txt_username.setText(model.getValueAt(selectedRow, 1).toString()); // Username
        txt_password.setText(model.getValueAt(selectedRow, 2).toString()); // Password
        txt_nama.setText(model.getValueAt(selectedRow, 3).toString());     // Nama
        txt_NIS.setText(model.getValueAt(selectedRow, 4).toString());      // NIS
        txt_kelas.setText(model.getValueAt(selectedRow, 5).toString());    // Kelas
        txt_tanggallahir.setText(model.getValueAt(selectedRow, 6).toString()); // Tanggal Lahir
        
        String jenisKelamin = model.getValueAt(selectedRow, 7).toString(); // Jenis Kelamin
        if ("Laki-laki".equals(jenisKelamin)) {
            rbLaki.setSelected(true);
            rbPerempuan.setSelected(false);
        } else if ("Perempuan".equals(jenisKelamin)) {
            rbPerempuan.setSelected(true);
            rbLaki.setSelected(false);
        } else {
            rbLaki.setSelected(false);
            rbPerempuan.setSelected(false);
        }
        
        txt_alamat.setText(model.getValueAt(selectedRow, 8).toString()); // Alamat
    }

    private void btnLIHATDATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIHATDATAActionPerformed
        loadTableData(); // Panggil metode untuk memuat ulang data
    }//GEN-LAST:event_btnLIHATDATAActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        updateSiswaData(); // Panggil metode untuk melakukan update
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
        saveSiswaData(); // Panggil metode untuk menyimpan data
    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
        deleteSiswaData(); // Panggil metode untuk menghapus data
    }//GEN-LAST:event_btnHAPUSActionPerformed

    // --- Metode Bantuan untuk Operasi Database ---

    // Metode untuk memuat data ke tabel
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tblDATASISWA.getModel();
        model.setRowCount(0); // Bersihkan baris yang ada

        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dimuat.");
                return;
            }

            String sql = "SELECT idanggota, username, password, nama, nis, kelas, tanggal_lahir, jeniskelamin, alamat FROM anggota ORDER BY idanggota ASC";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("idanggota"),
                    rs.getString("username"),
                    rs.getString("password"),
                    rs.getString("nama"),  
                    rs.getString("nis"),
                    rs.getString("kelas"),
                    rs.getDate("tanggal_lahir"), // Menggunakan getDate() untuk DATE
                    rs.getString("jeniskelamin"),
                    rs.getString("alamat")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data siswa: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }
    
    // Metode untuk menyimpan data siswa baru
    private void saveSiswaData() {
        // String idanggota = txt_idanggota.getText(); // ID Anggota tidak perlu diambil karena SERIAL
        String username = txt_username.getText().trim();
        String password = new String(txt_password.getText().trim()); // Ambil password sebagai String
        String nama = txt_nama.getText().trim();
        String nis = txt_NIS.getText().trim();
        String kelas = txt_kelas.getText().trim();
        String tanggallahirStr = txt_tanggallahir.getText().trim();
        String alamat = txt_alamat.getText().trim();
        String jeniskelamin = "";
        if (rbLaki.isSelected()) {
            jeniskelamin = "Laki-laki";
        } else if (rbPerempuan.isSelected()) {
            jeniskelamin = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(this, "Jenis Kelamin harus dipilih.");
            return;
        }

        if (username.isEmpty() || password.isEmpty() || nama.isEmpty() || nis.isEmpty() || kelas.isEmpty() || tanggallahirStr.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom input harus diisi.");
            return;
        }

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rsGeneratedKeys = null; // Untuk mengambil ID yang dihasilkan

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat disimpan.");
                return;
            }
            
            // Konversi tanggal lahir dari String ke java.sql.Date
            Date tanggallahirSql = null;
            try {
                tanggallahirSql = Date.valueOf(tanggallahirStr); // Format YYYY-MM-DD
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Format Tanggal Lahir tidak valid. Gunakan YYYY-MM-DD.");
                return;
            }

            // Kolom idanggota TIDAK perlu disertakan karena SERIAL
            String sql = "INSERT INTO anggota (username, password, nama, nis, kelas, tanggal_lahir, jeniskelamin, alamat) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            // Menggunakan Statement.RETURN_GENERATED_KEYS untuk mendapatkan ID yang baru dibuat
            pst = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, nama);
            pst.setString(4, nis);
            pst.setString(5, kelas);
            pst.setDate(6, tanggallahirSql); // Menggunakan setDate()
            pst.setString(7, jeniskelamin);
            pst.setString(8, alamat);
            
            pst.executeUpdate();

            // Mengambil ID yang baru dihasilkan
            rsGeneratedKeys = pst.getGeneratedKeys();
            int newIdAnggota = -1;
            if (rsGeneratedKeys.next()) {
                newIdAnggota = rsGeneratedKeys.getInt(1); // Ambil ID dari kolom pertama
            }

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            clearFormFields(); // Mengosongkan form
            loadTableData(); // Muat ulang data tabel
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data siswa (SQL Error): " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rsGeneratedKeys != null) rsGeneratedKeys.close();
                if (pst != null) pst.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    // Metode untuk menghapus data siswa
    private void deleteSiswaData() {
        int selectedRow = tblDATASISWA.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!");
            return;
        }

        // Ambil idanggota dari kolom pertama tabel (kolom 0)
        String idanggotaStr = tblDATASISWA.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data siswa dengan ID " + idanggotaStr + "?", "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Connection con = null;
            PreparedStatement pst = null;
            try {
                con = Koneksi.getConnection();
                if (con == null) {
                    JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dihapus.");
                    return;
                }

                String sql = "DELETE FROM anggota WHERE idanggota = ?";
                pst = con.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(idanggotaStr)); // Menggunakan setInt()
                
                int rowsAffected = pst.executeUpdate();
                
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data siswa berhasil dihapus!");
                    loadTableData(); // Muat ulang data tabel
                    clearFormFields(); // Bersihkan form
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data siswa. Data tidak ditemukan.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID Anggota tidak valid.");
            } catch (SQLException e) {
                // Tangani Foreign Key Constraint Violation (misal jika ada data absen/nilai yang terkait)
                if (e.getSQLState().startsWith("23")) { // SQLState untuk integrity constraint violation
                    JOptionPane.showMessageDialog(this, "Tidak dapat menghapus siswa karena ada data terkait di tabel lain (misal: absen, nilai, laporan). Hapus data terkait terlebih dahulu.", "Kesalahan Penghapusan", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data siswa (SQL Error): " + e.getMessage());
                }
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
                e.printStackTrace();
            } finally {
                try {
                    if (pst != null) pst.close();
                    if (con != null) con.close();
                } catch (SQLException ex) {
                    System.err.println("Gagal menutup resource database: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }
        }
    }

    // Metode untuk memperbarui data siswa
    private void updateSiswaData() {
        int selectedRow = tblDATASISWA.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diperbarui di tabel.");
            return;
        }
        
        String idanggotaStr = txt_idanggota.getText().trim();
        String username = txt_username.getText().trim();
        String password = new String(txt_password.getPassword()); // Ambil password dari JPasswordField
        String nama = txt_nama.getText().trim();
        String nis = txt_NIS.getText().trim();
        String kelas = txt_kelas.getText().trim();
        String tanggallahirStr = txt_tanggallahir.getText().trim();
        String alamat = txt_alamat.getText().trim();
        String jeniskelamin = "";
        if (rbLaki.isSelected()) {
            jeniskelamin = "Laki-laki";
        } else if (rbPerempuan.isSelected()) {
            jeniskelamin = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(this, "Jenis Kelamin harus dipilih.");
            return;
        }

        if (idanggotaStr.isEmpty() || username.isEmpty() || password.isEmpty() || nama.isEmpty() || nis.isEmpty() || kelas.isEmpty() || tanggallahirStr.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom input harus diisi untuk pembaruan.");
            return;
        }
        
        Connection con = null;
        PreparedStatement pstmt = null;

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat diperbarui.");
                return;
            }

            int idanggota = Integer.parseInt(idanggotaStr);
            
            // Konversi tanggal lahir dari String ke java.sql.Date
            Date tanggallahirSql = null;
            try {
                tanggallahirSql = Date.valueOf(tanggallahirStr); // Format YYYY-MM-DD
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Format Tanggal Lahir tidak valid. Gunakan YYYY-MM-DD.");
                return;
            }
            
            // Query UPDATE. Pastikan nama kolom sesuai DB PostgreSQL
            // Perhatikan bahwa username dan password juga diupdate di sini.
            String sql = "UPDATE anggota SET username = ?, password = ?, nama = ?, nis = ?, kelas = ?, tanggal_lahir = ?, jeniskelamin = ?, alamat = ? WHERE idanggota = ?";
            pstmt = con.prepareStatement(sql);
            
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            pstmt.setString(3, nama);
            pstmt.setString(4, nis);
            pstmt.setString(5, kelas);
            pstmt.setDate(6, tanggallahirSql);
            pstmt.setString(7, jeniskelamin);
            pstmt.setString(8, alamat);
            pstmt.setInt(9, idanggota); // WHERE clause
            
            int rowsUpdated = pstmt.executeUpdate();
            
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data siswa berhasil diperbarui!");
                loadTableData(); // Muat ulang data tabel
                clearFormFields(); // Bersihkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data siswa. ID Anggota tidak ditemukan.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Anggota tidak valid.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data siswa (SQL Error): " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    // Metode untuk membersihkan input form
    private void clearFormFields() {
        txt_idanggota.setText("");
        txt_username.setText("");
        txt_password.setText("");
        txt_nama.setText("");
        txt_NIS.setText("");
        txt_kelas.setText("");
        txt_tanggallahir.setText("");
        txt_alamat.setText("");
        buttonGroup1.clearSelection(); // Mengosongkan pilihan radio button
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          int idAdmin = 1; // ID Admin dummy untuk pengujian mandiri

            AdminDataSiswa cpage = new AdminDataSiswa(idAdmin);
            cpage.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLIHATDATA;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tblDATASISWA;
    private javax.swing.JTextField txt_NIS;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idanggota;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_tanggallahir;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}