/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;
import config.Koneksi; // Import kelas Koneksi kamu
import java.sql.Connection;
// import java.sql.DriverManager; // Tidak diperlukan lagi
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// import java.sql.Connection; // Duplikat
// import java.sql.DriverManager; // Duplikat
import java.sql.PreparedStatement;
// import java.sql.ResultSet; // Duplikat
// import java.sql.SQLException; // Duplikat
import javax.swing.*;
// import java.awt.event.ActionEvent; // Duplikat
// import java.awt.event.ActionListener; // Duplikat
// import java.sql.*; // Duplikat, sudah ada import spesifik
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fitri
 */
public class AdminDataNilai extends javax.swing.JFrame {
    private int idAdmin;
    
    /**
     * Creates new form AdminDataNilai
     */
    public AdminDataNilai(int idAdmin) {
        this.idAdmin = idAdmin;
        initComponents();
        setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
        loadTableData(); // Muat data awal saat frame dibuat
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATANILAI = new javax.swing.JTable();
        btnLIHATNILAI = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idnilai = new javax.swing.JTextField();
        txt_idanggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_UH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSIMPAN = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();
        btnKEMBALI = new javax.swing.JButton();
        txt_UTS = new javax.swing.JTextField();
        txt_UAS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Data Nilai"); // Menambahkan judul window

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA NILAI");

        tblDATANILAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Nilai", "ID Anggota", "Nama", "NIS", "Kelas", "Nilai UH", "Nilai UTS", "Nilai UAS", "Nilai Akhir" // Menyesuaikan kolom
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, false // Memungkinkan edit nilai
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        // Menambahkan listener untuk mengisi form saat baris tabel diklik
        tblDATANILAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDATANILAIMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDATANILAI);

        btnLIHATNILAI.setText("REFRESH DATA"); // Mengubah teks
        btnLIHATNILAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIHATNILAIActionPerformed(evt);
            }
        });

        btnUPDATE.setText("PERBARUI"); // Mengubah teks
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Nilai");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Id Anggota");

        txt_idnilai.setEditable(false); // ID Nilai biasanya di-generate otomatis
        
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nilai Ulangan Harian");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nilai Ujian Tengah Semester");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nilai Ujian Akhir Semester");

        btnSIMPAN.setText("SIMPAN");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        btnHAPUS.setText("HAPUS");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHAPUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUPDATE)
                .addGap(18, 18, 18)
                .addComponent(btnLIHATNILAI)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(txt_UH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSIMPAN)
                        .addGap(200, 200, 200))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_UH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnSIMPAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLIHATNILAI)
                    .addComponent(btnUPDATE)
                    .addComponent(btnHAPUS))
                .addGap(26, 26, 26))
        );

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_UAS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_UTS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKEMBALI))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKEMBALI)
                .addGap(39, 39, 39)
                .addComponent(txt_UTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_UAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        dispose();
        AdminDashboard guestPage = new AdminDashboard(idAdmin);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void tblDATANILAIMouseClicked(java.awt.event.MouseEvent evt) {                                      
        int selectedRow = tblDATANILAI.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblDATANILAI.getModel();

        txt_idnilai.setText(model.getValueAt(selectedRow, 0).toString()); // ID Nilai
        txt_idanggota.setText(model.getValueAt(selectedRow, 1).toString()); // ID Anggota
        txt_UH.setText(model.getValueAt(selectedRow, 5).toString()); // Nilai UH
        txt_UTS.setText(model.getValueAt(selectedRow, 6).toString()); // Nilai UTS
        txt_UAS.setText(model.getValueAt(selectedRow, 7).toString()); // Nilai UAS
    }

    private void btnLIHATNILAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIHATNILAIActionPerformed
        loadTableData(); // Panggil metode untuk memuat ulang data
    }//GEN-LAST:event_btnLIHATNILAIActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        updateNilaiData(); // Panggil metode untuk melakukan update
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
        saveNilaiData(); // Panggil metode untuk menyimpan data
    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
        deleteNilaiData(); // Panggil metode untuk menghapus data
    }//GEN-LAST:event_btnHAPUSActionPerformed

    // --- Metode Bantuan untuk Operasi Database ---

    // Metode untuk memuat data ke tabel
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tblDATANILAI.getModel();
        model.setRowCount(0); // Bersihkan baris yang ada

        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dimuat.");
                return;
            }

            // Query untuk mengambil data nilai beserta nama, NIS, dan kelas dari anggota
            String sql = "SELECT n.idnilai, n.idanggota, a.nama, a.nis, a.kelas, " +
                         "n.nilaiUH, n.nilaiUTS, n.nilaiUAS, n.nilaiAkhir " +
                         "FROM nilai n JOIN anggota a ON n.idanggota = a.idanggota ORDER BY n.idnilai ASC";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("idnilai"),
                    rs.getInt("idanggota"),
                    rs.getString("nama"),
                    rs.getString("nis"),
                    rs.getString("kelas"),
                    rs.getDouble("nilaiUH"),
                    rs.getDouble("nilaiUTS"),
                    rs.getDouble("nilaiUAS"),
                    rs.getDouble("nilaiAkhir")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data nilai: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    // Metode untuk menyimpan data nilai baru
    private void saveNilaiData() {
        // String idnilai = txt_idnilai.getText().trim(); // Tidak perlu karena SERIAL
        String idanggotaStr = txt_idanggota.getText().trim();
        String nilaiUHStr = txt_UH.getText().trim();
        String nilaiUTSStr = txt_UTS.getText().trim();
        String nilaiUASStr = txt_UAS.getText().trim();

        if (idanggotaStr.isEmpty() || nilaiUHStr.isEmpty() || nilaiUTSStr.isEmpty() || nilaiUASStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom input nilai harus diisi.");
            return;
        }

        Connection con = null;
        PreparedStatement pstAnggota = null;
        PreparedStatement insertPst = null;
        PreparedStatement pstAbsen = null;
        ResultSet rsAnggota = null;
        ResultSet rsAbsen = null;

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat disimpan.");
                return;
            }

            int idanggota = Integer.parseInt(idanggotaStr);
            double nilaiUH = Double.parseDouble(nilaiUHStr);
            double nilaiUTS = Double.parseDouble(nilaiUTSStr);
            double nilaiUAS = Double.parseDouble(nilaiUASStr);

            // 1. Cek apakah idanggota valid dan ada
            String sqlCheckAnggota = "SELECT nama, nis, kelas FROM anggota WHERE idanggota = ?";
            pstAnggota = con.prepareStatement(sqlCheckAnggota);
            pstAnggota.setInt(1, idanggota);
            rsAnggota = pstAnggota.executeQuery();
            
            String nama = "";
            String nis = "";
            String kelas = "";
            if (rsAnggota.next()) {
                nama = rsAnggota.getString("nama");
                nis = rsAnggota.getString("nis");
                kelas = rsAnggota.getString("kelas");
            } else {
                JOptionPane.showMessageDialog(this, "ID Anggota tidak ditemukan. Silakan masukkan ID Anggota yang valid.");
                return;
            }

            // 2. Ambil jumlah kehadiran dari tabel absen (jika diperlukan untuk nilai akhir)
            int jumlahkehadiran = 0;
            String sqlGetAbsen = "SELECT jumlahkehadiran FROM absen WHERE idanggota = ?";
            pstAbsen = con.prepareStatement(sqlGetAbsen);
            pstAbsen.setInt(1, idanggota);
            rsAbsen = pstAbsen.executeQuery();
            if (rsAbsen.next()) {
                jumlahkehadiran = rsAbsen.getInt("jumlahkehadiran");
            } else {
                // Opsional: berikan pesan jika data absen tidak ada atau asumsikan 0
                // JOptionPane.showMessageDialog(this, "Data absensi tidak ditemukan untuk ID Anggota ini. Nilai akhir mungkin tidak akurat.");
            }

            // 3. Hitung nilai akhir (pastikan rumus ini sesuai dengan kebutuhan Anda)
            // Rumus dari kode Anda sebelumnya: double nilaiAkhir = rataNilai + ((absen * 0.7f) / 3);
            double rataNilai = (nilaiUH + nilaiUTS + nilaiUAS) / 3.0;
            double nilaiAbsenKontribusi = (jumlahkehadiran * 0.7) / 3.0; // Menggunakan 0.7f sebagai double
            double nilaiAkhir = rataNilai + nilaiAbsenKontribusi;

            // 4. Simpan ke tabel nilai (idnilai otomatis karena SERIAL)
            String insertSQL = "INSERT INTO nilai (idanggota, nilaiUH, nilaiUTS, nilaiUAS, nilaiAkhir) VALUES (?, ?, ?, ?, ?)";
            insertPst = con.prepareStatement(insertSQL);
            insertPst.setInt(1, idanggota);
            insertPst.setDouble(2, nilaiUH);
            insertPst.setDouble(3, nilaiUTS);
            insertPst.setDouble(4, nilaiUAS);
            insertPst.setDouble(5, nilaiAkhir);

            insertPst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Nilai berhasil ditambahkan!");

            clearFormFields(); // Reset form
            loadTableData(); // Muat ulang data tabel

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Nilai atau ID Anggota harus berupa angka.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan nilai (SQL Error): " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Tutup semua resource
            try {
                if (rsAnggota != null) rsAnggota.close();
                if (pstAnggota != null) pstAnggota.close();
                if (rsAbsen != null) rsAbsen.close();
                if (pstAbsen != null) pstAbsen.close();
                if (insertPst != null) insertPst.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    // Metode untuk menghapus data nilai
    private void deleteNilaiData() {
        int selectedRow = tblDATANILAI.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!");
            return;
        }

        // Ambil idnilai dari kolom pertama tabel (kolom 0)
        String idnilaiStr = tblDATANILAI.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus nilai dengan ID " + idnilaiStr + "?", "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Connection con = null;
            PreparedStatement pst = null;
            try {
                con = Koneksi.getConnection();
                if (con == null) {
                    JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dihapus.");
                    return;
                }

                String sql = "DELETE FROM nilai WHERE idnilai = ?"; // Hapus berdasarkan idnilai
                pst = con.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(idnilaiStr));
                
                int rowsAffected = pst.executeUpdate();
                
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data nilai berhasil dihapus!");
                    loadTableData(); // Muat ulang data tabel
                    clearFormFields(); // Bersihkan form
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data nilai. ID Nilai tidak ditemukan.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID Nilai tidak valid.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus nilai (SQL Error): " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
                e.printStackTrace();
            } finally {
                try {
                    if (pst != null) pst.close();
                    if (con != null) con.close();
                } catch (SQLException ex) {
                    System.err.println("Gagal menutup resource database: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }
        }
    }

    // Metode untuk memperbarui data nilai
    private void updateNilaiData() {
        int selectedRow = tblDATANILAI.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diperbarui di tabel.");
            return;
        }
        
        String idnilaiStr = txt_idnilai.getText().trim();
        String idanggotaStr = txt_idanggota.getText().trim();
        String nilaiUHStr = txt_UH.getText().trim();
        String nilaiUTSStr = txt_UTS.getText().trim();
        String nilaiUASStr = txt_UAS.getText().trim();

        if (idnilaiStr.isEmpty() || idanggotaStr.isEmpty() || nilaiUHStr.isEmpty() || nilaiUTSStr.isEmpty() || nilaiUASStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom input nilai harus diisi untuk pembaruan.");
            return;
        }
        
        Connection con = null;
        PreparedStatement pstmt = null;
        PreparedStatement pstAbsen = null;
        ResultSet rsAbsen = null;

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat diperbarui.");
                return;
            }

            int idnilai = Integer.parseInt(idnilaiStr);
            int idanggota = Integer.parseInt(idanggotaStr);
            double nilaiUH = Double.parseDouble(nilaiUHStr);
            double nilaiUTS = Double.parseDouble(nilaiUTSStr);
            double nilaiUAS = Double.parseDouble(nilaiUASStr);

            // Ambil jumlah kehadiran untuk perhitungan nilai akhir
            int jumlahkehadiran = 0;
            String sqlGetAbsen = "SELECT jumlahkehadiran FROM absen WHERE idanggota = ?";
            pstAbsen = con.prepareStatement(sqlGetAbsen);
            pstAbsen.setInt(1, idanggota);
            rsAbsen = pstAbsen.executeQuery();
            if (rsAbsen.next()) {
                jumlahkehadiran = rsAbsen.getInt("jumlahkehadiran");
            }

            // Hitung nilai akhir yang diperbarui
            double rataNilai = (nilaiUH + nilaiUTS + nilaiUAS) / 3.0;
            double nilaiAbsenKontribusi = (jumlahkehadiran * 0.7) / 3.0;
            double nilaiAkhir = rataNilai + nilaiAbsenKontribusi;

            // Query UPDATE. Pastikan nama kolom sesuai DB PostgreSQL
            String sql = "UPDATE nilai SET idanggota = ?, nilaiUH = ?, nilaiUTS = ?, nilaiUAS = ?, nilaiAkhir = ? WHERE idnilai = ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setInt(1, idanggota);
            pstmt.setDouble(2, nilaiUH);
            pstmt.setDouble(3, nilaiUTS);
            pstmt.setDouble(4, nilaiUAS);
            pstmt.setDouble(5, nilaiAkhir);
            pstmt.setInt(6, idnilai); // WHERE clause
            
            int rowsUpdated = pstmt.executeUpdate();
            
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data nilai berhasil diperbarui!");
                loadTableData(); // Muat ulang data tabel
                clearFormFields(); // Bersihkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data nilai. ID Nilai tidak ditemukan.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Nilai atau ID harus berupa angka.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui nilai (SQL Error): " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Tutup semua resource
            try {
                if (rsAbsen != null) rsAbsen.close();
                if (pstAbsen != null) pstAbsen.close();
                if (pstmt != null) pstmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    // Metode untuk membersihkan input form
    private void clearFormFields() {
        txt_idnilai.setText("");
        txt_idanggota.setText("");
        txt_UH.setText("");
        txt_UTS.setText("");
        txt_UAS.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          int idAdmin = 1; // ID Admin dummy untuk pengujian mandiri

            AdminDataNilai cpage = new AdminDataNilai(idAdmin);
            cpage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLIHATNILAI;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDATANILAI;
    private javax.swing.JTextField txt_UAS;
    private javax.swing.JTextField txt_UH;
    private javax.swing.JTextField txt_UTS;
    private javax.swing.JTextField txt_idanggota;
    private javax.swing.JTextField txt_idnilai;
    // End of variables declaration//GEN-END:variables
}