/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fitri
 */
public class AdminDataAbsensi extends javax.swing.JFrame {
    private int idAdmin;

    /**
     * Creates new form AdminDataAbsensi
     */
    public AdminDataAbsensi(int idAdmin) {
         this.idAdmin = idAdmin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKEMBALI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblABSENSI = new javax.swing.JTable();
        btnLIHATABSENSI = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idabsen = new javax.swing.JTextField();
        txt_idanggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_jumlahkehadiran = new javax.swing.JTextField();
        txt_jumlahalfa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_jumlahsakit = new javax.swing.JTextField();
        txt_jumlahizin = new javax.swing.JTextField();
        btnSIMPAN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA ABSENSI");

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        tblABSENSI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIS", "Kelas", "Hadir", "Alfa", "Sakit", "Izin"
            }
        ));
        jScrollPane1.setViewportView(tblABSENSI);

        btnLIHATABSENSI.setText("LIHAT ABSENSI");
        btnLIHATABSENSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIHATABSENSIActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnHAPUS.setText("HAPUS");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Absen");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Id Anggota");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hadir");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Alfa");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Sakit");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Izin");

        btnSIMPAN.setText("SIMPAN");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHAPUS)
                .addGap(38, 38, 38)
                .addComponent(btnUPDATE)
                .addGap(36, 36, 36)
                .addComponent(btnLIHATABSENSI)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKEMBALI))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_idabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_jumlahalfa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_jumlahsakit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_jumlahkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_jumlahizin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnSIMPAN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKEMBALI)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idabsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_jumlahalfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_jumlahsakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_jumlahkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_jumlahizin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSIMPAN)
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLIHATABSENSI)
                    .addComponent(btnUPDATE)
                    .addComponent(btnHAPUS))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLIHATABSENSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIHATABSENSIActionPerformed
       // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) tblABSENSI.getModel();
    // Clear any existing rows
    model.setRowCount(0);

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
     Statement stmt = con.createStatement();
     ResultSet rs = stmt.executeQuery(
            "SELECT a.idanggota, a.nama, a.nis, a.kelas, ab.jumlahkehadiran, ab.jumlahalfa, ab.jumlahsakit, ab.jumlahizin " +
            "FROM absen ab " +
            "JOIN anggota a ON ab.idanggota = a.idanggota")) {

    // Initialize a counter for the "No" column
    int no = 1;

    // Iterate over the result set and add rows to the table
    while (rs.next()) {
                model.addRow(new Object[]{
                        no++,                              // No
                        rs.getString("nama"),              // Nama
                        rs.getString("nis"),               // NIS
                        rs.getString("kelas"),             // Kelas
                        rs.getInt("jumlahkehadiran"),      // Kehadiran
                        rs.getInt("jumlahalfa"),           // Alfa
                        rs.getInt("jumlahsakit"),          // Sakit
                        rs.getInt("jumlahizin")            // Izin
                });
            }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    e.printStackTrace();  // Optional: for debugging purposes
}

    }//GEN-LAST:event_btnLIHATABSENSIActionPerformed

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminDashboard guestPage = new AdminDashboard(idAdmin);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
        loadDataForm();
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
        // TODO add your handling code here:
        try {
    // Ambil data dari form
    String idabsen = txt_idabsen.getText();
    String idanggota = txt_idanggota.getText();
    String jumlahHadir = txt_jumlahkehadiran.getText();
    String jumlahAlfa = txt_jumlahalfa.getText();
    String jumlahSakit = txt_jumlahsakit.getText();
    String jumlahIzin = txt_jumlahizin.getText();

    // Ambil data nama dan NIS berdasarkan idanggota
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sekolah_smp", "root", "");
    String sqlAnggota = "SELECT nama, nis, kelas FROM anggota WHERE idanggota = ?";
    PreparedStatement pstAnggota = con.prepareStatement(sqlAnggota);
    pstAnggota.setString(1, idanggota);
    ResultSet rs = pstAnggota.executeQuery();
    
    String nama = "";
    String nis = "";
    String kelas = "";
    if (rs.next()) {
        nama = rs.getString("nama");
        nis = rs.getString("nis");
        kelas = rs.getString("kelas");
    } else {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        return;
    }

    // SQL untuk menyimpan data absensi
    String sqlAbsen = "INSERT INTO absen (idabsen, idanggota, jumlahkehadiran, jumlahalfa, jumlahsakit, jumlahizin) VALUES (?, ?, ?, ?, ?, ?)";
    PreparedStatement pstAbsen = con.prepareStatement(sqlAbsen);
    pstAbsen.setString(1, idabsen);
    pstAbsen.setString(2, idanggota);
    pstAbsen.setString(3, jumlahHadir);
    pstAbsen.setString(4, jumlahAlfa);
    pstAbsen.setString(5, jumlahSakit);
    pstAbsen.setString(6, jumlahIzin);
    pstAbsen.executeUpdate();

    // Menampilkan data di tabel tblABSENSI
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblABSENSI.getModel();
    int no = model.getRowCount() + 1;
    model.addRow(new Object[]{
        no, nama, nis, kelas, jumlahHadir, jumlahAlfa, jumlahSakit, jumlahIzin
    });

    // Mengosongkan form setelah data disimpan
    txt_idabsen.setText("");
    txt_idanggota.setText("");
    txt_jumlahkehadiran.setText("");
    txt_jumlahalfa.setText("");
    txt_jumlahsakit.setText("");
    txt_jumlahizin.setText("");

    JOptionPane.showMessageDialog(null, "Data absensi berhasil disimpan!");

    // Tutup koneksi
    pstAbsen.close();
    pstAnggota.close();
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal menyimpan data absensi: " + e.getMessage());
}

    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
        // TODO add your handling code here:
        try {
    int selectedRow = tblABSENSI.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
        return;
    }

    String idanggota = tblABSENSI.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(
        null,
        "Yakin ingin menghapus absen untuk data ini?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM absen WHERE idanggota = ?";
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sekolah_smp", "root", "");
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, idanggota);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data absen berhasil dihapus!");
            loadDataForm();
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Gagal menghapus absen (SQL Error): " + e.getMessage());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
}
    }//GEN-LAST:event_btnHAPUSActionPerformed
    private void loadDataForm() {
        DefaultTableModel model = (DefaultTableModel) tblABSENSI.getModel();
        int selectedRow = tblABSENSI.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris yang ingin diperbarui.");
        return;
    }
   
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
             PreparedStatement pstmt = con.prepareStatement(    
             "UPDATE absen SET jumlahkehadiran = ?, jumlahalfa = ?, jumlahsakit = ?, jumlahizin = ? WHERE idabsen = ?")) {
        // Retrieve values from the selected row in tblDATAABSEN
        int idabsen = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
        String hadirStr= model.getValueAt(selectedRow, 4).toString();
        String alfaStr = model.getValueAt(selectedRow, 5).toString();
        String sakitStr = model.getValueAt(selectedRow, 6).toString();
        String izinStr = model.getValueAt(selectedRow,7).toString();
        
        int jumlahkehadiran = parseValidCount(hadirStr);
        int jumlahalfa = parseValidCount(alfaStr);
        int jumlahsakit = parseValidCount(sakitStr);
        int jumlahizin = parseValidCount(izinStr);
         // Setting values to PreparedStatement
        pstmt.setInt(1, jumlahkehadiran);
        pstmt.setInt(2, jumlahalfa);
        pstmt.setInt(3, jumlahsakit);
        pstmt.setInt(4, jumlahizin);
        pstmt.setInt(5, idabsen);
        
        int rowsUpdate = pstmt.executeUpdate();
        
        if (rowsUpdate > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui.");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal memperbarui data.");
        }
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat update data: " + e.getMessage());
    }    
    }
    private int parseValidCount(String value) {
        try {
            int num = Integer.parseInt(value);
            if (num < 0) return -1;
            return num;
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          int idAdmin = 123;

            AdminDataAbsensi cpage = new AdminDataAbsensi(idAdmin);
            cpage.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLIHATABSENSI;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblABSENSI;
    private javax.swing.JTextField txt_idabsen;
    private javax.swing.JTextField txt_idanggota;
    private javax.swing.JTextField txt_jumlahalfa;
    private javax.swing.JTextField txt_jumlahizin;
    private javax.swing.JTextField txt_jumlahkehadiran;
    private javax.swing.JTextField txt_jumlahsakit;
    // End of variables declaration//GEN-END:variables
}
