/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;

import config.Koneksi; // Import kelas Koneksi kamu
import java.sql.Connection;
// import java.sql.DriverManager; // Tidak diperlukan lagi
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// import java.sql.Connection; // Duplikat
// import java.sql.DriverManager; // Duplikat
import java.sql.PreparedStatement;
// import java.sql.ResultSet; // Duplikat
// import java.sql.SQLException; // Duplikat
// import javax.swing.JOptionPane; // Duplikat
import javax.swing.*;
// import java.awt.event.ActionEvent; // Duplikat
// import java.awt.event.ActionListener; // Duplikat
// import java.sql.*; // Duplikat, sudah ada import spesifik
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fitri
 */
public class AdminDataAbsensi extends javax.swing.JFrame {
    private int idAdmin;

    /**
     * Creates new form AdminDataAbsensi
     */
    public AdminDataAbsensi(int idAdmin) {
        this.idAdmin = idAdmin;
        initComponents();
        setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
        // Memuat data awal saat frame dibuat (opsional, tapi disarankan)
        loadTableData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKEMBALI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblABSENSI = new javax.swing.JTable();
        btnLIHATABSENSI = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idabsen = new javax.swing.JTextField();
        txt_idanggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_jumlahkehadiran = new javax.swing.JTextField();
        txt_jumlahalfa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_jumlahsakit = new javax.swing.JTextField();
        txt_jumlahizin = new javax.swing.JTextField();
        btnSIMPAN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Data Absensi"); // Menambahkan judul window

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA ABSENSI");

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        tblABSENSI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Absen", "ID Anggota", "Nama", "NIS", "Kelas", "Hadir", "Sakit", "Izin" // Menyesuaikan dengan kolom DB
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true // Memungkinkan edit di kolom jumlah
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        // Menambahkan listener untuk mengisi form saat baris tabel diklik
        tblABSENSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblABSENSIMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblABSENSI);

        btnLIHATABSENSI.setText("REFRESH DATA"); // Mengubah teks agar lebih jelas
        btnLIHATABSENSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIHATABSENSIActionPerformed(evt);
            }
        });

        btnUPDATE.setText("PERBARUI"); // Mengubah teks agar lebih jelas
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnHAPUS.setText("HAPUS");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Absen");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Id Anggota");

        txt_idabsen.setEditable(false); // ID Absen biasanya di-generate otomatis
        txt_idabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idabsenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hadir");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Alfa"); // Ini akan diubah untuk 'Sakit' nanti jika diperlukan

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Sakit");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Izin");

        btnSIMPAN.setText("SIMPAN");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHAPUS)
                .addGap(38, 38, 38)
                .addComponent(btnUPDATE)
                .addGap(36, 36, 36)
                .addComponent(btnLIHATABSENSI)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKEMBALI))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_idabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_jumlahalfa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_jumlahsakit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_jumlahkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_jumlahizin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnSIMPAN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKEMBALI)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idabsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_jumlahalfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_jumlahsakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_jumlahkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_jumlahizin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSIMPAN)
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLIHATABSENSI)
                    .addComponent(btnUPDATE)
                    .addComponent(btnHAPUS))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLIHATABSENSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIHATABSENSIActionPerformed
       loadTableData(); // Panggil metode untuk memuat ulang data tabel
    }//GEN-LAST:event_btnLIHATABSENSIActionPerformed

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        dispose();
        AdminDashboard guestPage = new AdminDashboard(idAdmin);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void tblABSENSIMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // Mendapatkan baris yang dipilih
        int selectedRow = tblABSENSI.getSelectedRow();
        if (selectedRow == -1) {
            return; // Tidak ada baris yang dipilih
        }

        DefaultTableModel model = (DefaultTableModel) tblABSENSI.getModel();

        // Mengisi JTextField dengan data dari baris yang dipilih
        txt_idabsen.setText(model.getValueAt(selectedRow, 0).toString()); // Kolom 'ID Absen'
        txt_idanggota.setText(model.getValueAt(selectedRow, 1).toString()); // Kolom 'ID Anggota'
        txt_jumlahkehadiran.setText(model.getValueAt(selectedRow, 5).toString()); // Kolom 'Hadir'
        txt_jumlahalfa.setText(model.getValueAt(selectedRow, 6).toString()); // Kolom 'Sakit' (di database Anda jumlahlahsakit)
        txt_jumlahsakit.setText(model.getValueAt(selectedRow, 7).toString()); // Kolom 'Izin' (di database Anda jumlahizin)
        txt_jumlahizin.setText(model.getValueAt(selectedRow, 7).toString()); // Kolom 'Izin' (ini duplikat jika tidak ada kolom alfa)
    }

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        updateAbsensiData(); // Panggil metode untuk melakukan update
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
        saveAbsensiData(); // Panggil metode untuk menyimpan data
    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
        deleteAbsensiData(); // Panggil metode untuk menghapus data
    }//GEN-LAST:event_btnHAPUSActionPerformed

    private void txt_idabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idabsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idabsenActionPerformed

    // --- Metode Bantuan untuk Operasi Database ---

    // Metode untuk memuat data ke tabel
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tblABSENSI.getModel();
        model.setRowCount(0); // Bersihkan baris yang ada

        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dimuat.");
                return;
            }

            // JOIN dengan tabel anggota untuk mendapatkan nama, NIS, dan kelas
            // Pastikan nama kolom 'jumlahalfa' di database adalah 'jumlahlahsakit' jika itu yang Anda maksud
            String sql = "SELECT ab.idabsen, ab.idanggota, a.nama, a.nis, a.kelas, " +
                         "ab.jumlahkehadiran, ab.jumlahlahsakit, ab.jumlahizin " + // Gunakan jumlahlahsakit
                         "FROM absen ab JOIN anggota a ON ab.idanggota = a.idanggota ORDER BY ab.idabsen ASC";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("idabsen"),          // ID Absen
                    rs.getInt("idanggota"),        // ID Anggota
                    rs.getString("nama"),          // Nama Siswa
                    rs.getString("nis"),           // NIS Siswa
                    rs.getString("kelas"),         // Kelas Siswa
                    rs.getInt("jumlahkehadiran"),  // Hadir
                    rs.getInt("jumlahlahsakit"),   // Sakit (seperti di DB)
                    rs.getInt("jumlahizin")        // Izin
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data absensi: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }
    
    // Metode untuk menyimpan data absensi baru
    private void saveAbsensiData() {
        // ID Absen (txt_idabsen) tidak perlu diambil dari form karena SERIAL
        // String idabsen = txt_idabsen.getText().trim();
        String idanggotaStr = txt_idanggota.getText().trim();
        String jumlahHadirStr = txt_jumlahkehadiran.getText().trim();
        String jumlahAlfaStr = txt_jumlahalfa.getText().trim(); // Ini akan menjadi 'Sakit'
        String jumlahIzinStr = txt_jumlahizin.getText().trim();

        if (idanggotaStr.isEmpty() || jumlahHadirStr.isEmpty() || jumlahAlfaStr.isEmpty() || jumlahIzinStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi.");
            return;
        }

        try {
            int idanggota = Integer.parseInt(idanggotaStr);
            int jumlahHadir = Integer.parseInt(jumlahHadirStr);
            int jumlahlahsakit = Integer.parseInt(jumlahAlfaStr); // Perbaikan nama kolom
            int jumlahizin = Integer.parseInt(jumlahIzinStr);

            Connection con = null;
            PreparedStatement pstAbsen = null;
            PreparedStatement pstAnggota = null;
            ResultSet rsAnggota = null;

            try {
                con = Koneksi.getConnection();
                if (con == null) {
                    JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat disimpan.");
                    return;
                }
                
                // Cek apakah idanggota valid dan ada di tabel anggota
                String sqlCheckAnggota = "SELECT idanggota FROM anggota WHERE idanggota = ?";
                pstAnggota = con.prepareStatement(sqlCheckAnggota);
                pstAnggota.setInt(1, idanggota);
                rsAnggota = pstAnggota.executeQuery();
                
                if (!rsAnggota.next()) {
                    JOptionPane.showMessageDialog(this, "ID Anggota tidak ditemukan. Silakan masukkan ID Anggota yang valid.");
                    return;
                }

                // SQL untuk menyimpan data absensi baru
                // Kolom idabsen TIDAK perlu disertakan karena SERIAL
                String sqlAbsen = "INSERT INTO absen (idanggota, jumlahkehadiran, jumlahlahsakit, jumlahizin) VALUES (?, ?, ?, ?)";
                pstAbsen = con.prepareStatement(sqlAbsen);
                pstAbsen.setInt(1, idanggota);
                pstAbsen.setInt(2, jumlahHadir);
                pstAbsen.setInt(3, jumlahlahsakit); // Menggunakan jumlahlahsakit
                pstAbsen.setInt(4, jumlahizin);
                
                pstAbsen.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data absensi berhasil disimpan!");
                clearFormFields(); // Mengosongkan form
                loadTableData(); // Muat ulang data tabel
                
            } finally {
                try {
                    if (rsAnggota != null) rsAnggota.close();
                    if (pstAnggota != null) pstAnggota.close();
                    if (pstAbsen != null) pstAbsen.close();
                    if (con != null) con.close();
                } catch (SQLException ex) {
                    System.err.println("Gagal menutup resource database: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Hadir, Sakit, Izin, atau ID Anggota harus berupa angka.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data absensi (SQL Error): " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Metode untuk menghapus data absensi
    private void deleteAbsensiData() {
        int selectedRow = tblABSENSI.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!");
            return;
        }

        // Ambil idabsen dari kolom pertama tabel (kolom 0)
        String idabsenStr = tblABSENSI.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus absensi dengan ID " + idabsenStr + "?", "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Connection con = null;
            PreparedStatement pst = null;
            try {
                con = Koneksi.getConnection();
                if (con == null) {
                    JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dihapus.");
                    return;
                }

                String sql = "DELETE FROM absen WHERE idabsen = ?";
                pst = con.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(idabsenStr));
                
                int rowsAffected = pst.executeUpdate();
                
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data absensi berhasil dihapus!");
                    loadTableData(); // Muat ulang data tabel
                    clearFormFields(); // Bersihkan form
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data absensi. Data tidak ditemukan.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID Absen tidak valid.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus absensi (SQL Error): " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
                e.printStackTrace();
            } finally {
                try {
                    if (pst != null) pst.close();
                    if (con != null) con.close();
                } catch (SQLException ex) {
                    System.err.println("Gagal menutup resource database: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }
        }
    }

    // Metode untuk memperbarui data absensi
    private void updateAbsensiData() {
        int selectedRow = tblABSENSI.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diperbarui di tabel.");
            return;
        }
        
        String idabsenStr = txt_idabsen.getText().trim();
        String idanggotaStr = txt_idanggota.getText().trim();
        String jumlahHadirStr = txt_jumlahkehadiran.getText().trim();
        String jumlahSakitStr = txt_jumlahalfa.getText().trim(); // Ini adalah 'Sakit'
        String jumlahIzinStr = txt_jumlahizin.getText().trim();

        if (idabsenStr.isEmpty() || idanggotaStr.isEmpty() || jumlahHadirStr.isEmpty() || jumlahSakitStr.isEmpty() || jumlahIzinStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi untuk pembaruan.");
            return;
        }
        
        Connection con = null;
        PreparedStatement pstmt = null;

        try {
            int idabsen = Integer.parseInt(idabsenStr);
            int idanggota = Integer.parseInt(idanggotaStr);
            int jumlahkehadiran = Integer.parseInt(jumlahHadirStr);
            int jumlahlahsakit = Integer.parseInt(jumlahSakitStr); // Perbaikan nama kolom
            int jumlahizin = Integer.parseInt(jumlahIzinStr);

            con = Koneksi.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat diperbarui.");
                return;
            }
            
            // Query UPDATE. Pastikan nama kolom 'jumlahalfa' di database adalah 'jumlahlahsakit'
            String sql = "UPDATE absen SET idanggota = ?, jumlahkehadiran = ?, jumlahlahsakit = ?, jumlahizin = ? WHERE idabsen = ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setInt(1, idanggota);
            pstmt.setInt(2, jumlahkehadiran);
            pstmt.setInt(3, jumlahlahsakit); // Menggunakan jumlahlahsakit
            pstmt.setInt(4, jumlahizin);
            pstmt.setInt(5, idabsen);
            
            int rowsUpdated = pstmt.executeUpdate();
            
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data absensi berhasil diperbarui!");
                loadTableData(); // Muat ulang data tabel
                clearFormFields(); // Bersihkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data absensi. ID Absen tidak ditemukan.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input ID, Hadir, Sakit, atau Izin harus berupa angka.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui absensi (SQL Error): " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    // Metode untuk membersihkan input form
    private void clearFormFields() {
        txt_idabsen.setText("");
        txt_idanggota.setText("");
        txt_jumlahkehadiran.setText("");
        txt_jumlahalfa.setText(""); // Sesuaikan dengan nama kolom yang benar
        txt_jumlahsakit.setText("");
        txt_jumlahizin.setText("");
    }
    
    // Metode main untuk pengujian terpisah
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          int idAdmin = 1; // ID Admin dummy untuk pengujian mandiri

            AdminDataAbsensi cpage = new AdminDataAbsensi(idAdmin);
            cpage.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLIHATABSENSI;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblABSENSI;
    private javax.swing.JTextField txt_idabsen;
    private javax.swing.JTextField txt_idanggota;
    private javax.swing.JTextField txt_jumlahalfa;
    private javax.swing.JTextField txt_jumlahizin;
    private javax.swing.JTextField txt_jumlahkehadiran;
    private javax.swing.JTextField txt_jumlahsakit;
    // End of variables declaration//GEN-END:variables
}