/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fitri
 */
public class AdminRekomendasi extends javax.swing.JFrame {
private int idAdmin;
    /**
     * Creates new form AdminRekomendasi
     */
    public AdminRekomendasi(int idAdmin) {
        this.idAdmin = idAdmin;
        initComponents();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATAREKOMENDASI = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnKEMBALI = new javax.swing.JButton();
        btnREKOMENDASI = new javax.swing.JButton();
        btnCETAK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDATAREKOMENDASI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIS", "Kelas", "Rekomendasi"
            }
        ));
        jScrollPane1.setViewportView(tblDATAREKOMENDASI);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Rekomendasi");

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        btnREKOMENDASI.setText("LIHAT REKOMENDASI");
        btnREKOMENDASI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREKOMENDASIActionPerformed(evt);
            }
        });

        btnCETAK.setText("CETAK");
        btnCETAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCETAKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKEMBALI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCETAK)
                                .addGap(18, 18, 18)
                                .addComponent(btnREKOMENDASI)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKEMBALI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnREKOMENDASI)
                    .addComponent(btnCETAK))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminDashboard guestPage = new AdminDashboard (idAdmin);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void btnCETAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCETAKActionPerformed
        // TODO add your handling code here:
        try {
    InputStream reportStream = getClass().getResourceAsStream("/Report/ReportRekomendasi.jasper");

    if (reportStream == null) {
        throw new FileNotFoundException("Report .jasper tidak ditemukan!");
    }

    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
    
    HashMap<String, Object> parameters = new HashMap<>();
    parameters.put("idanggota", idAdmin);

    JasperPrint print = JasperFillManager.fillReport(reportStream, parameters, con);
    JasperViewer viewer = new JasperViewer(print, false);
    viewer.setVisible(true);
    
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Terjadi error: " + e.getMessage());
}
    }//GEN-LAST:event_btnCETAKActionPerformed

    private void btnREKOMENDASIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREKOMENDASIActionPerformed
        // TODO add your handling code here:
        loadDataForm();
    }//GEN-LAST:event_btnREKOMENDASIActionPerformed
    private void loadDataForm() {
    DefaultTableModel model = (DefaultTableModel) tblDATAREKOMENDASI.getModel();
    model.setRowCount(0);

    String sql = "SELECT a.nama, a.nis, a.kelas, ab.jumlahkehadiran, n.nilaiUH, n.nilaiUTS, n.nilaiUAS " +
                 "FROM anggota a " +
                 "JOIN absen ab ON a.idanggota = ab.idanggota " +
                 "JOIN nilai n ON a.idanggota = n.idanggota";

    final int TOTAL_HARI = 30;

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
         PreparedStatement pst = conn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        int nomor = 1;  // Inisialisasi nomor urut

        while (rs.next()) {
            String nama = rs.getString("nama");
            String nis = rs.getString("nis");
            String kelas = rs.getString("kelas");
            int kehadiran = rs.getInt("jumlahkehadiran");
            double nilaiUH = rs.getDouble("nilaiUH");
            double nilaiUTS = rs.getDouble("nilaiUTS");
            double nilaiUAS = rs.getDouble("nilaiUAS");

            double rataNilai = (nilaiUH + nilaiUTS + nilaiUAS) / 3.0;
            double nilaiAbsensi = (kehadiran * 0.7) / 3.0;
            double nilaiAkhir = rataNilai + nilaiAbsensi;
            int tidakHadir = TOTAL_HARI - kehadiran;

            String rekomendasi;
            if (nilaiAkhir >= 85 && tidakHadir <= 2) {
                rekomendasi = "Siswa Berprestasi";
            } else if (nilaiAkhir >= 70 && tidakHadir <= 5) {
                rekomendasi = "Siswa Berbakat";
            } else if (tidakHadir > 5) {
                rekomendasi = "Kurang Presensi";
            } else {
                rekomendasi = "Perlu Pendampingan";
            }

            model.addRow(new Object[]{
                nomor++,  // Nomor urut
                nama,
                nis,
                kelas,
                rekomendasi
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        e.printStackTrace();
    }
}

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                 // Simulasikan idPasien yang didapat dari hasil query atau input lainnya
            int idAdmin = 123; // Ganti dengan nilai idPasien yang sesuai dari hasil query

            AdminRekomendasi cpage = new AdminRekomendasi(idAdmin);
            cpage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCETAK;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnREKOMENDASI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDATAREKOMENDASI;
    // End of variables declaration//GEN-END:variables
}
