/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fitri
 */
public class AdminDataNilai extends javax.swing.JFrame {
    private int idAdmin;
    
    /**
     * Creates new form AdminDataNilai
     */
    public AdminDataNilai(int idAdmin) {
        this.idAdmin = idAdmin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATANILAI = new javax.swing.JTable();
        btnLIHATNILAI = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idnilai = new javax.swing.JTextField();
        txt_idanggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_UH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSIMPAN = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();
        btnKEMBALI = new javax.swing.JButton();
        txt_UTS = new javax.swing.JTextField();
        txt_UAS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA NILAI");

        tblDATANILAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIS", "Kelas", "Nilai UH", "Nilai UTS", "Nilai UAS", "Nilai Akhir"
            }
        ));
        jScrollPane1.setViewportView(tblDATANILAI);

        btnLIHATNILAI.setText("LIHAT NILAI");
        btnLIHATNILAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIHATNILAIActionPerformed(evt);
            }
        });

        btnUPDATE.setText("UPDATE");
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Nilai");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Id Anggota");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nilai Ulangan Harian");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nilai Ujian Tengah Semester");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nilai Ujian Akhir Semester");

        btnSIMPAN.setText("SIMPAN");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        btnHAPUS.setText("HAPUS");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHAPUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUPDATE)
                .addGap(18, 18, 18)
                .addComponent(btnLIHATNILAI)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(txt_UH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSIMPAN)
                        .addGap(200, 200, 200))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_UH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnSIMPAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLIHATNILAI)
                    .addComponent(btnUPDATE)
                    .addComponent(btnHAPUS))
                .addGap(26, 26, 26))
        );

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_UAS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_UTS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKEMBALI))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKEMBALI)
                .addGap(39, 39, 39)
                .addComponent(txt_UTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_UAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminDashboard guestPage = new AdminDashboard(idAdmin);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void btnLIHATNILAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIHATNILAIActionPerformed
        // TODO add your handling code here:
DefaultTableModel model = (DefaultTableModel) tblDATANILAI.getModel();
// Clear any existing rows
model.setRowCount(0);

try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
     Statement stmt = con.createStatement();
     ResultSet rs = stmt.executeQuery(
            "SELECT n.idnilai, a.nama, a.nis, a.kelas, n.nilaiUH, " +
            "n.nilaiUTS, n.nilaiUAS, n.nilaiAkhir " +
            "FROM nilai n " +
            "JOIN anggota a ON n.idanggota = a.idanggota")) {

    // Iterate over the result set and add rows to the table
    while (rs.next()) {
        model.addRow(new Object[] {
            rs.getString("idnilai"),        // No dari idanggota
            rs.getString("nama"),           // Nama
            rs.getString("nis"),            // NIS
            rs.getString("kelas"),          // Kelas
            rs.getDouble("nilaiUH"),         // Nilai UH
            rs.getDouble("nilaiUTS"),        // Nilai UTS
            rs.getDouble("nilaiUAS"),        // Nilai UAS
            rs.getDouble("nilaiAkhir")       // Nilai Akhir
        });
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    e.printStackTrace();  // Optional: for debugging purposes
}

                    
    }//GEN-LAST:event_btnLIHATNILAIActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
        loadDataForm();
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
        // TODO add your handling code here:
        try {
    String idnilai = txt_idnilai.getText().trim();
    String idanggota = txt_idanggota.getText().trim();
    double nilaiUH = Double.parseDouble(txt_UH.getText());
    double nilaiUTS = Double.parseDouble(txt_UTS.getText());
    double nilaiUAS = Double.parseDouble(txt_UAS.getText());

    // Ambil nama, NIS, dan absen dari database
    String nama = "";
    String nis = "";
    String kelas = "";
    int absen = 0;

    String sql = "SELECT a.nama, a.nis, a.kelas, ab.jumlahkehadiran " +
                 "FROM anggota a " +
                 "JOIN absen ab ON a.idanggota = ab.idanggota " +
                 "WHERE a.idanggota = ?";

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sekolah_smp", "root", "");
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, idanggota);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            nama = rs.getString("nama");
            nis = rs.getString("nis");
            kelas = rs.getString("kelas");
            absen = rs.getInt("jumlahkehadiran");
        } else {
            JOptionPane.showMessageDialog(null, "ID Anggota atau data absen tidak ditemukan!");
            return;
        }

        // Hitung nilai akhir
        double rataNilai = (nilaiUH + nilaiUTS + nilaiUAS) / 3;
        double nilaiAkhir = rataNilai + ((absen * 0.7f) / 3);

        // Simpan ke tabel nilai
        String insertSQL = "INSERT INTO nilai (idnilai, idanggota, nilaiUH, nilaiUTS, nilaiUAS, nilaiAkhir) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement insertPst = con.prepareStatement(insertSQL)) {
            insertPst.setString(1, idnilai);
            insertPst.setString(2, idanggota);
            insertPst.setDouble(3, nilaiUH);
            insertPst.setDouble(4, nilaiUTS);
            insertPst.setDouble(5, nilaiUAS);
            insertPst.setDouble(6, nilaiAkhir);

            insertPst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Nilai berhasil ditambahkan!");

            // Tambahkan ke tabel tampilan
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblDATANILAI.getModel();
            int no = model.getRowCount() + 1;
            model.addRow(new Object[]{
                no, nama, nis, kelas, nilaiUH, nilaiUTS, nilaiUAS, nilaiAkhir
            });

            // Reset form
            txt_idnilai.setText("");
            txt_idanggota.setText("");
            txt_UH.setText("");
            txt_UTS.setText("");
            txt_UAS.setText("");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal menyimpan nilai: " + e.getMessage());
}

    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
        // TODO add your handling code here:
        try {
    int selectedRow = tblDATANILAI.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
        return;
    }

    String idanggota = tblDATANILAI.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(
        null,
        "Yakin ingin menghapus nilai untuk data ini?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM nilai WHERE idanggota = ?";
        
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sekolah_smp", "root", "");
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, idanggota);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data nilai berhasil dihapus!");
            loadDataForm();
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Gagal menghapus nilai (SQL Error): " + e.getMessage());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
}

    }//GEN-LAST:event_btnHAPUSActionPerformed
   private void loadDataForm() {
    DefaultTableModel model = (DefaultTableModel) tblDATANILAI.getModel();
    int selectedRow = tblDATANILAI.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris data nilai yang ingin diperbarui.");
        return;
    }

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "")) {

        int idnilai = Integer.parseInt(model.getValueAt(selectedRow, 0).toString()); // kolom 0 = idnilai
        String nis = model.getValueAt(selectedRow, 2).toString(); // kolom 2 = NIS

        // Ambil idanggota berdasarkan NIS
        int idanggota = 0;
        try (PreparedStatement stmt = con.prepareStatement("SELECT idanggota FROM anggota WHERE nis = ?")) {
            stmt.setString(1, nis);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                idanggota = rs.getInt("idanggota");
            } else {
                JOptionPane.showMessageDialog(null, "ID Anggota tidak ditemukan untuk NIS: " + nis);
                return;
            }
        }

        // Ambil jumlah kehadiran dari tabel absen berdasarkan idanggota
        int jumlahHadir = 0;
        try (PreparedStatement stmt = con.prepareStatement("SELECT jumlahkehadiran FROM absen WHERE idanggota = ?")) {
            stmt.setInt(1, idanggota);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                jumlahHadir = rs.getInt("jumlahkehadiran");
            }
        }

        // Ambil nilai dari GUI
        double nilaiUH = Double.parseDouble(model.getValueAt(selectedRow, 4).toString());
        double nilaiUTS = Double.parseDouble(model.getValueAt(selectedRow, 5).toString());
        double nilaiUAS = Double.parseDouble(model.getValueAt(selectedRow, 6).toString());

        // Hitung nilai akhir
        double nilaiRata = (nilaiUH + nilaiUTS + nilaiUAS) / 3.0;
        double nilaiAbsen = (0.7 * jumlahHadir) / 3.0;
        double nilaiAkhir = nilaiRata + nilaiAbsen;

        // Update ke tabel nilai berdasarkan idnilai
        try (PreparedStatement pstmt = con.prepareStatement(
            "UPDATE nilai SET nilaiUH = ?, nilaiUTS = ?, nilaiUAS = ?, nilaiAkhir = ? WHERE idnilai = ?")) {

            pstmt.setDouble(1, nilaiUH);
            pstmt.setDouble(2, nilaiUTS);
            pstmt.setDouble(3, nilaiUAS);
            pstmt.setDouble(4, nilaiAkhir);
            pstmt.setInt(5, idnilai);

            int rows = pstmt.executeUpdate();
            if (rows > 0) {
                model.setValueAt(nilaiAkhir, selectedRow, 7); // kolom 7 = Nilai Akhir
                JOptionPane.showMessageDialog(null, "Nilai berhasil diperbarui.");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui nilai untuk ID Nilai: " + idnilai);
            }
        }

    } catch (SQLException | NumberFormatException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat update nilai: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          int idAdmin = 123;

            AdminDataNilai cpage = new AdminDataNilai(idAdmin);
            cpage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLIHATNILAI;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDATANILAI;
    private javax.swing.JTextField txt_UAS;
    private javax.swing.JTextField txt_UH;
    private javax.swing.JTextField txt_UTS;
    private javax.swing.JTextField txt_idanggota;
    private javax.swing.JTextField txt_idnilai;
    // End of variables declaration//GEN-END:variables
}
