/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;

import config.Koneksi; // Import kelas Koneksi kamu
import java.sql.Connection;
// import java.sql.DriverManager; // Tidak diperlukan lagi
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// import javax.swing.*; // Sudah tercakup oleh import spesifik

/**
 *
 * @author fitri
 */
public class DataAbsensi extends javax.swing.JFrame {
    private int idanggota;
    // private Connection con; // Hapus ini, koneksi diambil dan ditutup per method

    /**
     * Creates new form DataAbsensi
     */
    public DataAbsensi(int idanggota) {
        initComponents();
        setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
        this.idanggota = idanggota;
        // Tidak perlu koneksi di constructor, ambil setiap kali dibutuhkan dan tutup
        loadDataForm(); // Memuat data saat frame diinisialisasi
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_kelas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_hadir = new javax.swing.JTextField();
        text_alfa = new javax.swing.JTextField();
        text_sakit = new javax.swing.JTextField();
        text_izin = new javax.swing.JTextField();
        btnKEMBALI = new javax.swing.JButton();
        btnLIHATABSENSI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Absensi Siswa"); // Menambahkan judul window

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nama");

        text_nama.setEditable(false); // Tidak bisa di-edit
        
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Kelas");

        text_kelas.setEditable(false); // Tidak bisa di-edit
        
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Hadir");

        text_hadir.setEditable(false); // Tidak bisa di-edit
        
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Alfa (Sakit)"); // Mengubah label agar sesuai dengan jumlahlahsakit

        text_alfa.setEditable(false); // Tidak bisa di-edit
        
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Sakit (Izin)"); // Mengubah label agar sesuai dengan jumlahizin

        text_sakit.setEditable(false); // Tidak bisa di-edit
        
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Izin"); // Ini adalah label untuk jumlahizin

        text_izin.setEditable(false); // Tidak bisa di-edit

        btnKEMBALI.setText("KEMBALI"); // Mengubah teks agar lebih umum
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        btnLIHATABSENSI.setText("REFRESH"); // Mengubah teks agar lebih umum
        btnLIHATABSENSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIHATABSENSIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_nama)
                    .addComponent(text_kelas)
                    .addComponent(text_hadir)
                    .addComponent(text_alfa)
                    .addComponent(text_sakit)
                    .addComponent(text_izin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLIHATABSENSI)
                .addGap(44, 44, 44)
                .addComponent(btnKEMBALI)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_hadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_alfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_sakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_izin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKEMBALI)
                    .addComponent(btnLIHATABSENSI))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        dispose();
        DataPage guestPage = new DataPage(idanggota);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void btnLIHATABSENSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIHATABSENSIActionPerformed
        loadDataForm(); // Panggil metode untuk memuat ulang data
    }//GEN-LAST:event_btnLIHATABSENSIActionPerformed

    // Metode untuk memuat data absensi siswa
    private void loadDataForm() {
        Connection con = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            con = Koneksi.getConnection(); // Menggunakan kelas Koneksi
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data tidak dapat dimuat.");
                return;
            }

            // Query untuk mendapatkan data absensi dan info anggota
            // Perhatikan: 'jumlahalfa' di kode asli Anda, di DB PostgreSQL ini adalah 'jumlahlahsakit'
            String query = "SELECT a.nama, a.kelas, ab.jumlahkehadiran, ab.jumlahlahsakit, ab.jumlahizin "
                         + "FROM absen ab "
                         + "JOIN anggota a ON ab.idanggota = a.idanggota "
                         + "WHERE ab.idanggota = ?";

            pstmt = con.prepareStatement(query);
            pstmt.setInt(1, idanggota); // idanggota sebagai parameter filter
            rs = pstmt.executeQuery();

            if (rs.next()) {
                text_nama.setText(rs.getString("nama"));
                text_kelas.setText(rs.getString("kelas"));
                text_hadir.setText(String.valueOf(rs.getInt("jumlahkehadiran")));
                text_alfa.setText(String.valueOf(rs.getInt("jumlahlahsakit"))); // Map ke 'Alfa' label
                text_sakit.setText(String.valueOf(rs.getInt("jumlahizin")));    // Map ke 'Sakit' label
                text_izin.setText(String.valueOf(rs.getInt("jumlahizin"))); // Duplikat, periksa label di GUI

            } else {
                JOptionPane.showMessageDialog(this, "Data absensi tidak ditemukan untuk ID anggota: " + idanggota);
                // Bersihkan field jika data tidak ditemukan
                text_nama.setText("");
                text_kelas.setText("");
                text_hadir.setText("");
                text_alfa.setText("");
                text_sakit.setText("");
                text_izin.setText("");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data absensi: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) { // Tangkap Exception umum untuk kesalahan tak terduga
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan tak terduga: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Pastikan semua resource ditutup di blok finally
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
                int idAnggota = 1; // ID Anggota dummy untuk pengujian mandiri. Ganti dengan ID yang ada di DB.
            DataAbsensi cpage = new DataAbsensi (idAnggota);
            cpage.setVisible(true);
               }
        });
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLIHATABSENSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_alfa;
    private javax.swing.JTextField text_hadir;
    private javax.swing.JTextField text_izin;
    private javax.swing.JTextField text_kelas;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_sakit;
    // End of variables declaration//GEN-END:variables
}