/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;

/**
 *
 * @author fitri
 */
public class DataRekomendasi extends javax.swing.JFrame {
    private int idanggota;
    private Connection con;
    
    /**
     * Creates new form DataRekomendasi
     */
    public DataRekomendasi(int idanggota) {
      initComponents();
        this.idanggota = idanggota;
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to database: " + e.getMessage());
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        text_kelas = new javax.swing.JTextField();
        text_rekomendasi = new javax.swing.JTextField();
        btnKEMBALI = new javax.swing.JButton();
        btnREKOMENDASI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Kelas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Rekomendasi");

        btnKEMBALI.setText("CLOSE");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        btnREKOMENDASI.setText("LIHAT REKOMENDASI");
        btnREKOMENDASI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREKOMENDASIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(199, 199, 199)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_nama)
                    .addComponent(text_kelas)
                    .addComponent(text_rekomendasi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnREKOMENDASI)
                .addGap(50, 50, 50)
                .addComponent(btnKEMBALI)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_rekomendasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKEMBALI)
                    .addComponent(btnREKOMENDASI))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        // TODO add your handling code here:
        dispose();
        DataPage guestPage = new DataPage(idanggota);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void btnREKOMENDASIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREKOMENDASIActionPerformed
        // TODO add your handling code here:
        loadDataForm();
    }//GEN-LAST:event_btnREKOMENDASIActionPerformed
    private void loadDataForm() {
    String sql = "SELECT a.nama, a.kelas, ab.jumlahkehadiran, n.nilaiUH, n.nilaiUTS, n.nilaiUAS, r.rekomendasi " +
                 "FROM rekomendasi r " +
                 "JOIN anggota a ON r.idanggota = a.idanggota " +
                 "JOIN absen ab ON r.idabsen = ab.idabsen " +
                 "JOIN nilai n ON r.idnilai = n.idnilai " +
                 "WHERE r.idanggota = ?";

    final int TOTAL_HARI = 30;

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sekolah_smp", "root", "");
         PreparedStatement pst = conn.prepareStatement(sql)) {

        pst.setInt(1, idanggota); // idanggota harus sudah terisi

        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                String nama = rs.getString("nama");
                String kelas = rs.getString("kelas");
                int kehadiran = rs.getInt("jumlahkehadiran");
                double nilaiUH = rs.getDouble("nilaiUH");
                double nilaiUTS = rs.getDouble("nilaiUTS");
                double nilaiUAS = rs.getDouble("nilaiUAS");
                String rekomendasiDb = rs.getString("rekomendasi");

                // Jika kolom rekomendasi di DB kosong, hitung secara dinamis:
                String rekomendasi;
                if (rekomendasiDb == null || rekomendasiDb.trim().isEmpty()) {
                    double rataNilai = (nilaiUH + nilaiUTS + nilaiUAS) / 3.0;
                    double nilaiAbsensi = (kehadiran * 0.7) / 3.0;
                    double nilaiAkhir = rataNilai + nilaiAbsensi;
                    int tidakHadir = TOTAL_HARI - kehadiran;

                    if (nilaiAkhir >= 85 && tidakHadir <= 2) {
                        rekomendasi = "Siswa Berprestasi";
                    } else if (nilaiAkhir >= 70 && tidakHadir <= 5) {
                        rekomendasi = "Siswa Berbakat";
                    } else if (tidakHadir > 5) {
                        rekomendasi = "Kurang Presensi";
                    } else {
                        rekomendasi = "Perlu Pendampingan";
                    }
                } else {
                    rekomendasi = rekomendasiDb;
                }

                // Tampilkan ke text field
                text_nama.setText(nama);
                text_kelas.setText(kelas);
                text_rekomendasi.setText(rekomendasi);

            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan untuk ID anggota: " + idanggota);
                // Clear field jika data tidak ditemukan
                text_nama.setText("");
                text_kelas.setText("");
                text_rekomendasi.setText("");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data rekomendasi: " + e.getMessage());
        e.printStackTrace();
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataRekomendasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                int idAnggota = 1; // Ganti dengan nilai idPasien yang sesuai dari hasil query
            DataAbsensi cpage = new DataAbsensi (idAnggota);
            cpage.setVisible(true);; // Menampilkan halaman Guest
               }
        });
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnREKOMENDASI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_kelas;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_rekomendasi;
    // End of variables declaration//GEN-END:variables
}
