/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sekolah;
import config.Koneksi; // Import kelas Koneksi kamu
import java.sql.Connection;
// import java.sql.DriverManager; // Tidak diperlukan lagi
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// import java.sql.Connection; // Duplikat
// import java.sql.DriverManager; // Duplikat
import java.sql.PreparedStatement;
// import java.sql.ResultSet; // Duplikat
// import java.sql.SQLException; // Duplikat
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
// import java.sql.*; // Duplikat
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author fitri
 */
public class GuruLaporan extends javax.swing.JFrame {
    int idGuru;

    /**
     * Creates new form GuruLaporan
     */
    public GuruLaporan(int idGuru) {
        this.idGuru = idGuru;
        initComponents();
        setLocationRelativeTo(null); // Menempatkan jendela di tengah layar
        loadTableData(); // Memuat data saat frame diinisialisasi
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKEMBALI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATALAPORAN = new javax.swing.JTable();
        btnLAPORAN = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Laporan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guru Laporan"); // Menambahkan judul window

        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Laporan");

        tblDATALAPORAN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}, // Menambahkan kolom internal ID
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Anggota", "Nama", "NIS", "Kelas", "Hadir", "Nilai UH", "Nilai UTS", "Nilai UAS", "Laporan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDATALAPORAN);

        btnLAPORAN.setText("REFRESH LAPORAN"); // Mengubah teks
        btnLAPORAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLAPORANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKEMBALI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLAPORAN, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKEMBALI)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLAPORAN)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        dispose();
        GuruDashboard guestPage = new GuruDashboard(idGuru);
        guestPage.setVisible(true);
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    private void btnLAPORANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLAPORANActionPerformed
        loadTableData(); // Panggil metode untuk memuat ulang data
    }//GEN-LAST:event_btnLAPORANActionPerformed

    // Metode untuk memuat data ke tabel
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tblDATALAPORAN.getModel();
        model.setRowCount(0); // Bersihkan baris yang ada

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        String sql = "SELECT a.idanggota, a.nama, a.nis, a.kelas, ab.jumlahkehadiran, n.nilaiUH, n.nilaiUTS, n.nilaiUAS " +
                     "FROM anggota a " +
                     "JOIN absen ab ON a.idanggota = ab.idanggota " +
                     "JOIN nilai n ON a.idanggota = n.idanggota ORDER BY a.idanggota ASC";

        final int TOTAL_HARI = 30;

        try {
            con = Koneksi.getConnection(); // Menggunakan kelas Koneksi
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal. Data laporan tidak dapat dimuat.");
                return;
            }
            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            int nomor = 1; // Inisialisasi nomor urut

            while (rs.next()) {
                String nama = rs.getString("nama");
                String nis = rs.getString("nis");
                String kelas = rs.getString("kelas");
                int kehadiran = rs.getInt("jumlahkehadiran");
                double nilaiUH = rs.getDouble("nilaiUH");
                double nilaiUTS = rs.getDouble("nilaiUTS");
                double nilaiUAS = rs.getDouble("nilaiUAS");

                double rataNilai = (nilaiUH + nilaiUTS + nilaiUAS) / 3.0;
                // Asumsi nilaiAbsensiPercent di sini adalah persentase kehadiran, bukan kontribusi ke nilai akhir
                // double nilaiAbsensiPercent = (kehadiran * 100.0) / TOTAL_HARI; // Tidak digunakan untuk laporan
                int absensiTidakMasuk = TOTAL_HARI - kehadiran;

                double nilaiAkhir = rataNilai; // Bisa ditambah bobot absensi jika diperlukan
                // Jika ingin menggunakan nilaiAkhir dari database, Anda perlu mengambilnya dari JOIN ke tabel nilai juga
                // n.nilaiAkhir

                // Buat laporan string sesuai logika yang kamu inginkan
                StringBuilder laporan = new StringBuilder();

                if (nilaiAkhir < 70) {
                    laporan.append("Nilai Rendah. ");
                }
                if (absensiTidakMasuk > 5) {
                    laporan.append("Sering tidak hadir.");
                }

                if (laporan.length() == 0) {
                    laporan.append("Tidak ada masalah.");
                }

                model.addRow(new Object[]{
                    nomor++,
                    rs.getInt("idanggota"), // ID Anggota (disimpan tapi mungkin tersembunyi)
                    nama,
                    nis,
                    kelas,
                    kehadiran,
                    nilaiUH,
                    nilaiUTS,
                    nilaiUAS,
                    laporan.toString()
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data laporan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                System.err.println("Gagal menutup resource database: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuruLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuruLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuruLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuruLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          int idGuru = 1; // ID Guru dummy untuk pengujian mandiri. Ganti dengan ID yang ada di DB.

            GuruLaporan cpage = new GuruLaporan(idGuru);
            cpage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnLAPORAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDATALAPORAN;
    // End of variables declaration//GEN-END:variables
}